#!/bin/sh

# e.g. `./run async.ts`

function setup
{
  [ -d "${WORK_DIR}" ] && rm -f ${WORK_DIR}/*.ts || :
}

function teardown
{
  cd "${ROOT_DIR}"
  rm -f ${WORK_DIR}/*.ts
  exit
}

function main
{
  mkdir -p "${WORK_DIR}"
  cp -f "${TARGET}" "${WORK_DIR}"
  cd "${WORK_DIR}"
  tsc
  node out/${TARGET%.ts}.js
}

set -e

ROOT_DIR="$(cd ${0%/*} && pwd)"
TARGET="$1"
WORK_DIR=./work

trap teardown SIGINT SIGHUP SIGKILL

setup
main
teardown
